FROM node:22.15 AS builder

RUN mkdir -p /tmp/build/

# Build app
COPY ./ /tmp/build/

WORKDIR /tmp/build
ENV NODE_ENV=production
RUN npm i

FROM node:22.15 AS final
ENV NODE_ENV=production
WORKDIR /opt/app
COPY --from=builder /tmp/build/ /opt/app/
