export const WORKFLOW_TYPES = {
  BALANCE: 'BALANCE',
  TRANSFER: 'TRANSFER',
  PRICE: 'PRICE',
  STAKESTONE: 'STAKESTONE',
  EVERY_PERIOD: 'EVERY_PERIOD',
} as const;

export const INTERVALS = {
  EVERY_PERIOD: 10,
  STAKESTONE: 10,
  PRICE: 10,
  BALANCE: 10,
  TRANSFER: 0,
};