export const WORKFLOW_TYPES = {
  BALANCE: 'BALANCE',
  TRANSFER: 'TRANSFER',
  PRICE: 'PRICE',
  STAKESTONE: 'STAKESTONE',
  EVERY_PERIOD: 'EVERY_PERIOD',
  STRESS_LOOP: 'STRESS_LOOP',
} as const;

export const INTERVALS = {
  [WORKFLOW_TYPES.EVERY_PERIOD]: 10,
  [WORKFLOW_TYPES.STAKESTONE]: 10,
  [WORKFLOW_TYPES.PRICE]: 10,
  [WORKFLOW_TYPES.BALANCE]: 10,
  [WORKFLOW_TYPES.TRANSFER]: 0,
  [WORKFLOW_TYPES.STRESS_LOOP]: -1, // infinite loop
};