name: Workflow Monitor

on:
  schedule:
    - cron: '*/30 * * * *'  # Run every 30 minutes
  workflow_dispatch:  # Allow manual trigger

jobs:
  monitor:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run workflow monitoring
      run: npm run monitor
      env:
        API_BASE_URL: ${{ secrets.API_BASE_URL }}
        API_TOKEN: ${{ secrets.API_TOKEN }}
        
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add public/data/
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "📊 Update workflow monitoring data [$(date -u +%Y-%m-%d\ %H:%M:%S)]"
          git push
        fi 